[package]
name = "winit_editor"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["vello"]
vello = ["dep:vello", "dep:pollster"]
tiny-skia = ["dep:tiny-skia", "dep:softbuffer", "dep:skrifa", "dep:bytemuck"]

[dependencies]
anyhow = "1.0.89"
winit = "0.30.5"
parley = { workspace = true, default-features = true, features = ["accesskit"] }
peniko = { workspace = true }
accesskit = { workspace = true }
accesskit_winit = "0.23"

# vello
vello = { version = "0.3.0", optional = true }
pollster = { version = "0.3.0", optional = true }

# tiny-skia
tiny-skia = { version = "0.11.4", optional = true }
softbuffer = { version = "0.4.6", optional = true }
skrifa = { workspace = true, optional = true }
bytemuck = { version = "1.19.0", optional = true }

[lints]
workspace = true

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30.5", features = ["android-native-activity"] }

[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))'.dependencies]
clipboard-rs = "0.1.11"
